### ISSUE TITLE
Deploying is adding/removing files that it shouldn't

### ISSUE THREAD

**Issue by bhamodi** [optimizely/developers.optimizely.com#144]
Hey @tscanlin - everytime I run `npm run deploy`, it seems to add or remove a bunch of unrelated files to the ones that I change in my commits. The files that get added/removed don't really make any sense and are completely unrelated. Some of these diffs are +/- 1000 lines. Do you know why deploying to `gh-pages` adds or removes a huge amount of unrelated lines?

**Comment by tscanlin** [comment]
Huge amount of unrelated lines or unrelated files?

Regardless, a major update was merged into the developer-dot repo today to refactor the docs and remove code samples moving them under the other categories instead. That landed today, so that probably caused most of this to happen.

Another factor could be that I'm not cleaning the build directory each time. This is a change I've been thinking about making for a while, but I just haven't gotten around to it. Now that you bring this up and based off the experiences of others I'll try to make that a higher priority.

Thanks for paying attention to this repo, I appreciate it! :)

**Comment by bhamodi** [comment]
@tscanlin - both unrelated lines and unrelated files.

I think cleaning out the build directory as part of every deploy command is the solution like you stated. I could help you look into doing this. :+1:
