### ISSUE TITLE
Adding API Token for interactive mode does not give any feedback that token is accepted

### ISSUE THREAD

**Issue by bexcitement** [optimizely/developers.optimizely.com#159]
I'm using interactive mode on the REST API docs to give some training and when I add my API token after clicking the "Enter API Token" button up in the upper right hand corner and hit enter there is no verification that my API token was received/accepted/valid, which is a bit confusing especially when the pane for interactive mode is blank at the top of the page.

cc @tscanlin @Bigspencey

**Comment by tscanlin** [comment]
Great suggestion! I will work on implementing this today. Thanks @bexcitement

**Comment by bexcitement** [comment]
Thanks @tscanlin!

**Comment by tscanlin** [comment]
@bexcitement so right now the only check / error state we have is for when users enter a blank api token. In which case there is an error message below the api token field. I can definitely add an "Ok" button / pressing enter to set the api token but making sure it's a valid token isn't known until the user tries to make a request.

Additionally, the api token field hides as soon as it's entered to get out of the user's way while they make a request so even if we did have an endpoint to validate api tokens (currently we don't) the field would likely be hidden before we'd have a chance to show them a success / token validation message.

Do you think having this extra validation is necessary or is this issue addressed by just adding a few more ways to submit the token, since currently it only submits/hides on blur when a user clicks outside the field?

**Comment by tscanlin** [comment]
For now I think this is a good step in the right direction:
https://github.com/optimizely/developers.optimizely.com/pull/160
